---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - MySQL-python
  become: yes

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775
  become: yes

- name: Create MariaDB PID directory
  file: path=/var/run/mysqld state=directory owner=mysql group=mysql mode=0775
  become: yes

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes
  become: yes

- name: Start firewalld
  service: name=firewalld state=started enabled=yes
  become: yes

- name: insert firewalld rule
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
  become: yes

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present
  become: yes

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
  become: yes
