---
# These tasks install http and the php modules.

- name: Install httpd and php
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - php
   - php-mysql
   - mod_ssl
  become: yes

- name: Install web role specific dependencies
  yum: name={{ item }} state=installed
  with_items:
   - git
  become: yes

- name: Start firewalld
  service: name=firewalld state=started enabled=yes
  become: yes

- name: insert firewalld rule for httpd
  firewalld: port={{ httpd_port }}/tcp permanent=true state=enabled immediate=yes
  become: yes

- name: http service state
  service: name=httpd state=started enabled=yes
  become: yes

- name: Creates directory
  file: path={{ item }} state=directory
  with_items:
    - /etc/ssl/crt
    - /etc/ssl/private
    - /etc/ssl/csr
  become: yes

- name: Create self-signed certificate, if configured.
  command: >
    openssl req -x509 -nodes -subj '/CN=localhost' -days 365
    -newkey rsa:4096 -sha256 -keyout /etc/ssl/private/localhost.key -out /etc/ssl/csr/localhost.csr
    creates=/etc/ssl/crt/localhost.crt
  become: yes

- name: Install main configuration file
  template:
    src: httpd.conf.j2
    dest: "{{ httpd_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  become: yes

- name: Install status configuration file
  template:
    src: etc_httpd_conf.d_status.conf.j2
    dest: "{{ httpd_status_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  when: httpd_StatusEnable
  become: yes

- name: Install mod_ssl configuration file
  template:
    src: ssl.conf.j2
    dest: "{{ httpd_ssl_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart httpd
  become: yes
