---
# This playbook deploys the whole application stack in this site.
- hosts: all

- name: apply common configuration to all nodes
  vars_files:
    - group_vars/all
  remote_user: ec2-user

  roles:
    - common

- name: deploy MySQL and configure the databases
  remote_user: ec2-user
  vars_files:
    - group_vars/all
    - group_vars/dbservers

  roles:
    - db

- name: configure and deploy the webservers and application code
  remote_user: ec2-user
  vars_files:
    - group_vars/all
    - group_vars/webservers

  roles:
    - web
